apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversion-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: conversion-api
  template:
    metadata:
      labels:
        app: conversion-api
    spec:
      containers:
        - name: conversion-api
          image: henriquesantoslopes/conversion-api:v1
          ports:
            - containerPort: 8080
